### ISSUE TITLE
make website https

### ISSUE THREAD

**Issue by suyash** [performancecopilot/pcp-website#5]
it is very easy to set up tls using certificates obtained from certbot (https://certbot.eff.org/) for free!

my principal motivation is that I am planning speed 1.0 and I want to support a canonical import path  (something like 'pcp.io/speed' instead of the current 'github.com/performancecopilot/speed')

but the 'go get' tool doesn't download packages over http unless an `-insecure` flag is specified

hence, it would be nice if the tls could be added to the website

**Comment by natoscott** [comment]
+1  - will look into it, thanks Suyash!

**Comment by webknjaz** [comment]
@natoscott 
https://pcp.io has invalid certificate currently.

GitHub now supports Let's Encrypt SSL natively, just enable it: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by natoscott** [comment]
Done!  Hooray - thanks @webknjaz
