### ISSUE TITLE
pcp.io/news.html: 404 not found

### ISSUE THREAD

**Issue by mavit** [performancecopilot/pcp-website#9]
The website footer links to http://pcp.io/news.html, but there is no such page.

**Comment by natoscott** [comment]
commit 53cfb8abfcab5d9f9546dfd8ad5e0285609caeab
Author: Nathan Scott <nathans@redhat.com>
Date:   Wed May 17 13:01:10 2017 +1000

    Drop outdated reference to news.html from the footer.
    
    We nowadays track highlights of the last few releases on the
    frontpage, and complete chapter and verse is at...
    https://github.com/performancecopilot/pcp/blob/master/CHANGELOG
    
    Resolves http://github.com/performancecopilot/pcp-website/issues/9
